- ju/_2133.java
- ju/_2293.java
- ju/_2579.java
- ju/_9461.java
- ju/_9465.java
> [Ju] week1,2

- ju/_2294.java
> [Ju] week2 나머지

- lee/week3/_12851.java
- lee/week3/_1759.java
- lee/week3/_2493.java
> [Jun] 3주차 문제풀이

- ju/_12851.java
- ju/_1697.java
- ju/_2133.java
- ju/_2493.java
> [Ju] week3

- lee/week4/_1309.java
- lee/week4/_15684.java
- lee/week4/_17090.java
> [Jun] 4주차 문제풀이

- ju/_14890.java
- ju/_17090.java
- ju/_2225.java
> [Ju] week4 보충

- lee/week4/_15684.java
- lee/week5/_14890.java
- lee/week5/_1726.java
- lee/week5/_2225.java
> [Jun] Week 5

- lee/week3/_12851.java
- lee/week5/_2225.java
- lee/week6/_10799.java
- lee/week6/_2812.java
> [Jun] week 6

- ju/week7/_11559.java
- ju/week7/_14502.java
- ju/week7/_4991.java
> [Ju] week7

- lee/week8/_10866.java
- lee/week8/_16234.java
- lee/week8/_17144.java
> [Jun] Week8 문제 풀이

- ju/week8/_10866.java
- ju/week8/_14503.java
- ju/week8/_17144.java
> [Ju] Week8 문제풀이

- ju/week9/_1520.java
- ju/week9/_16234.java
- ju/week9/_9935.java
> [Ju] Week9 문제 풀이

- lee/week9/_1520.java
- lee/week9/_9935.java
> [Jun] Week9

- ju/week10/_1987.java
- ju/week10/_5014.java
- ju/week10/_9019.java
> [Ju] Week10 문제 풀이

- lee/week10/_1987.java
- lee/week10/_5014.java
- lee/week10/_9019.java
> [Jun] 10주차 풀이

- ju/week11/_13459.java
- ju/week11/_13460.java
- ju/week11/_3055.java
> [Ju] Week11 문제 풀이

- lee/week12/_13913.java
- lee/week12/_17141.java
- lee/week12/_1965.java
- lee/week13/_11725.java
- lee/week13/_16918.java
- lee/week13/_2302.java
- lee/week13/_2606.java
- lee/week13/_2667.java
> [Jun] week12

- lee/week14/_2667.java
> [Jun] week13 

- ju/week13/_1328_not.java
- ju/week13/_16918.java
- ju/week13/_2302.java
> [Ju] Week 13 문제풀이

- ju/week14/_14923.java
- ju/week14/_2098_not.java
- ju/week14/_2667.java
> [Ju] week14 문제풀이

- ju/week15/_2631.java
--------------알고리즘 문제 종료--------------
자바 알고리즘 with 코틀린으로 공부하자고
> [Ju] Week15 1문제 풀이

- ju/week16/_2580.java
- ju/week16/_6593.java
> [Ju] Week16

- lee/week19/_17142.java
- lee/week19/_2096.java
- lee/week20/_12100.java
- lee/week20/_15685.java
> [Jun] week 19, 20

- ju/week20/_12100.java
> [Ju] Week20

- lee/week21/_16235.java
- lee/week21/_16236.java
> [Jun] week 21

- lee/week21/_16236.java
- lee/week22/_17143.java
- lee/week22/_17779.java
> [Jun] week 22

- lee/week23/_17822.java
- lee/week23/_17837.java
> [Jun] week 23

- lee/week24/_17825.java
- lee/week24/_20061.java
> [Jun] week24

- lee/week25/_19236.java
- lee/week25/_19237.java
> [Jun] week 25

- lee/week26/_20056.java
- lee/week26/_20057.java
> [Jun] week26

- lee/week27/_258711.java
- lee/week27/_258712.java
> [Jun] week27

- lee/week28/_20040.java
> [Jun] week28 

- lee/week30/_20046.java
- lee/week30/_20058.java
- lee/week30/_21608.java
> [Jun] week 30

- lee/week31/_20047.java
- lee/week31/_20170.java
> [Jun] week31
